#ifndef GLOBAL_DEFINES_H_
#define GLOBAL_DEFINES_H_

enum device_types_e {
	DEVICE_TYPE_INVALID = 0,
	DEVICE_TYPE_OSCAR,	// Level sensor (LTE connected)
	DEVICE_TYPE_ERNIE, 	// Underbin master (LTE connected)
	DEVICE_TYPE_ELMO 	// Underbin weight and RFID sensing
};

enum message_types_e {
	MESSAGE_TYPE_STATS_DATA = 0x00,
	MESSAGE_TYPE_RFID_DATA,
	MESSAGE_TYPE_ENV_DATA,
	MESSAGE_TYPE_RANGE_DATA,
	MESSAGE_TYPE_WEIGHT_DATA,
	MESSAGE_TYPE_WEIGHT_ZERO_DATA,
	MESSAGE_TYPE_FW_UPDATE_CHECK = 0x10,
	MESSAGE_TYPE_FW_UPDATE_BEGIN,
	MESSAGE_TYPE_FW_UPDATE_DATA,
	MESSAGE_TYPE_FW_UPDATE_END,
	MESSAGE_TYPE_DEPLOYED_UPDATE = 0x20,
	MESSAGE_TYPE_SIS_ADDR_UPDATE,
	MESSAGE_TYPE_PARAMS_UPDATE,
	MESSAGE_TYPE_NTP_UPDATE
};

#define BOOTLOADER_FW_UPGRADE_FLAG (0x00C0FFEE)

#endif /* GLOBAL_DEFINES_H_ */
