name: Run tests

on: [push]


jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
    - name: "Step 1 : Clone Git Repo into root directory"
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONS_PRIVATE_REPO_ACCESS }}
        submodules: recursive

    - name: "Step 2: Install CMake"
      run: sudo apt-get -y install cmake

    - name: "Step 3: Install gcc"
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install manpages-dev

    - name: "Step 4: Run tests"
      run: |
        cd Tests
        chmod +x run_tests.sh
        ./run_tests.sh